project:
  type: website
  output-dir: docs

website: 
 navbar:
  title: "Katelyn Vidal"
  left:
    - href: index.qmd
      text: Home
    - art.qmd
    - crochet.qmd
    - portfolio.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full
    

editor: visual

