---
title: "Portfolio"
---

Here are some writing pieces I did during my undergrad that I especially enjoyed working on. Hope you enjoy reading, and feel free to email me if you have any questions!
---

**ENV S 149 Food, Agriculture, and the Environment:**\
[“Filipino Cuisine with a side of...Colonialism?”](https://www.canva.com/design/DAF-O88u2ic/hI-bsnZ_OPX-USvyECXumg/view?utm_content=DAF-O88u2ic&utm_campaign=designshare&utm_medium=link&utm_source=editor)- Blog post

This blog post explores the history of Spanish colonialism in the Philippines and how this has impacted Filipino food and agriculture, along with the subsequent Westernization of Filipino cuisine and how this connects to increased health risks prevalent in Filipino communities in the US.
---

**ENV S 40 Critical Thinking and Evidence-Based Reasoning for the Environment:**\
[“The Origins of Fast Fashion”](https://drive.google.com/file/d/17m35kYVJ5oequeiMDDfMFr6xHT9mOWyL/view?usp=drive_link) - Zine

This zine is an investigation of our relationship with the environment and clothing and works to answer the question, “How has our relationship with the environment and clothing contributed to the rise of fast fashion.” It explores topics such as colonialism, capitalism, and consumerism and how this has impacted the environment and the fast fashion industry.
---

**ENV S 101 Ecosystem Services and Biodiversity:**\
[“The Kidneys of the Earth and the Hearts of California Native Americans”](https://docs.google.com/document/d/1t14RVw668NMsmsot6JohFtY5ki8dgayQqfUJzMm7yoc/edit?usp=drive_link) - Essay

This paper describes riparian wetlands and their ecological benefits, like erosion control and nitrogen removal, along with the cultural ecosystem services they provide, like the cultural and spiritual identity of California Native Americans. It also covers the effects of European colonization on riparian wetlands in CA and the importance of traditional ecological knowledge (TEK) and traditional resource management (TRM).
